name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/go-web-app:${{github.run_id}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  # First fix: Proper kubeconfig setup
    - name: Configure Kubernetes
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        set-context: current-context

  # Second fix: Verify cluster connection
    - name: Verify Cluster Access
      run: kubectl cluster-info

  # Third fix: Update image tags
    - name: Update Image in Deployment
      run: |
        sed -i "s|baby6ix|${{ secrets.DOCKERHUB_USERNAME }}|g" k8s/manifiests/deployment.yaml
        sed -i "s|IMAGE_TAG|${{ github.run_id }}|g" k8s/manifiests/deployment.yaml

  # Fourth fix: Proper manifest application
    - name: Deploy to Cluster
      run: kubectl apply -f k8s/manifiests/


