name: CI/CD

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.31.0'

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.K8S_KUBECONFIG }}" > $HOME/.kube/config

      - name: Check kubectl config
        run: kubectl config view

      - name: Debug Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/manifiests/deployment.yaml --validate=false
          kubectl apply -f ./k8s/manifiests/service.yaml --validate=false
          kubectl apply -f ./k8s/manifiests/ingress.yaml --validate=false

      - name: Wait for deployment to finish
        run: kubectl rollout status deployment/go-web-app