name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}  

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/manifiests/deployment.yaml
          kubectl apply -f ./k8s/manifiests/service.yaml
          kubectl apply -f ./k8s/manifiests/ingress.yaml

      - name: Wait for deployment to finish
        run: |
          kubectl rollout status deployment/go-web-app
