name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/go-web-app:${{github.run_id}}
  
  deploy:
    runs-on: ubuntu-latest
    needs: push  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update Image in Deployment
      run: |
        sed -i "s|baby6ix|${{ secrets.DOCKERHUB_USERNAME }}|g" k8s/manifiests/deployment.yaml
        sed -i "s|IMAGE_TAG|${{ github.run_id }}|g" k8s/manifiests/deployment.yaml

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure Kubernetes Cluster
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f k8s/manifiests/


